server:
  port: 8081
  contextPath: /banking
  
---
datasource:
 sampleapp:
   url: jdbc:h2:~/test
   username: SA
   password:
   driverClassName: org.h2.Driver
   defaultSchema:
   maxPoolSize: 10
   hibernate:
     hbm2ddl.method: create
     show_sql: true
     format_sql: true
     dialect: org.hibernate.dialect.H2Dialect
     
---
logging:
  level:
    org.springframework.web: ERROR
    com.ingenico: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
