 insert into DB_ACCOUNT(IBAN,CUSTNAME,BALANCE) values ('IBAN1','CUSTOMER1','1000');
 insert into DB_ACCOUNT(IBAN,CUSTNAME,BALANCE) values ('IBAN2','CUSTOMER2','2000');
 insert into DB_ACCOUNT(IBAN,CUSTNAME,BALANCE) values ('IBAN3','CUSTOMER3','3000');
 insert into DB_ACCOUNT(IBAN,CUSTNAME,BALANCE) values ('IBAN4','CUSTOMER3','4000');


